#!/usr/bin/env python3
import os
import shlex
import sys


def main() -> None:
    if len(sys.argv) > 1:
        command = sys.argv[1] if len(sys.argv) == 2 else shlex.join(sys.argv[1:])
    else:
        command = os.environ.get("STARTUP", "palworld-umu-start").strip() or "palworld-umu-start"
    os.chdir("/home/container")
    print(f":/home/container$ {command}", flush=True)
    os.execv("/bin/bash", ["bash", "-lc", command])


if __name__ == "__main__":
    main()
